name: Build cta_lib

on:
  push:
    tags:
      - 'cta_lib_*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Miniconda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH

      - name: Install conda-build
        run: |
          source $HOME/miniconda/etc/profile.d/conda.sh
          conda install -y conda-build setuptools

      - name: Build cta_lib
        run: |
          source $HOME/miniconda/etc/profile.d/conda.sh
          cd lib
          conda build conda-recipe
