/*.$file${.::seqCtrl.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: seqCtrl.qm
* File:  ${.::seqCtrl.c}
*
* This code has been generated by QM 5.0.1 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*.$endhead${.::seqCtrl.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "qpc.h"

#include "seqCtrl.h"

#include <epicsMutex.h>
#include <stdio.h>
#include <inttypes.h>


Q_DEFINE_THIS_FILE

/* type definition ---------------------------------------------------------*/
typedef struct {
    uint32_t cycles;
} RepetitionConfiguration;
void RepetitionConfigurationInit(RepetitionConfiguration* config) {
    config->cycles = 0;
}

typedef struct {
    enum StartMode mode;
    uint32_t moduloDivisor;
    uint32_t moduloOffset;
} StartConfiguration;
void StartConfigurationInit(StartConfiguration* config) {
    config->mode = START_IMMEDIATELY;
    config->moduloDivisor = 1;
    config->moduloOffset = 0;
}

typedef struct {
    uint32_t length;
    RepetitionConfiguration rep;
    StartConfiguration start;
} Configuration;
void ConfigurationInit(Configuration *config) {
    config->length = 0;
    RepetitionConfigurationInit(&config->rep);
    StartConfigurationInit(&config->start);
}

/* Active object class -----------------------------------------------------*/
/*.$declare${AOs::SeqCtrl} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::SeqCtrl} .........................................................*/
typedef struct {
/* protected: */
    QActive super;

/* private: */
    uint32_t index;
    uint32_t count;
    Configuration config;
} SeqCtrl;

/* protected: */
static QState SeqCtrl_initial(SeqCtrl * const me, QEvt const * const e);
static QState SeqCtrl_root(SeqCtrl * const me, QEvt const * const e);
static QState SeqCtrl_stopped(SeqCtrl * const me, QEvt const * const e);
static QState SeqCtrl_running(SeqCtrl * const me, QEvt const * const e);
static QState SeqCtrl_waiting(SeqCtrl * const me, QEvt const * const e);
static QState SeqCtrl_play(SeqCtrl * const me, QEvt const * const e);
/*.$enddecl${AOs::SeqCtrl} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/* Local objects -----------------------------------------------------------*/
static SeqCtrl l_seqCtrl;   /* storage for seqCtrl */
static QEvt const * l_SeqCtrlQueueSto[10];
static QF_MPOOL_EL(QEvt) l_qEvt[10];
static QF_MPOOL_EL(PulseIdEvt) l_evtStoStartOfSeq[10];

/* Global objects ----------------------------------------------------------*/
QMActive * const AO_SeqCtrl = &l_seqCtrl.super;
/*.$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*. Check for the minimum required QP version */
#if (QP_VERSION < 670U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 6.7.0 or higher required
#endif
/*.$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$define${AOs::g_config} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::g_config} ........................................................*/
Configuration g_config;
/*.$enddef${AOs::g_config} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$define${AOs::g_configMutex} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::g_configMutex} ...................................................*/
epicsMutexId g_configMutex;
/*.$enddef${AOs::g_configMutex} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/* config setter */
/*.$define${AOs::SetLength} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::SetLength} .......................................................*/
void SetLength(uint32_t length) {
    epicsMutexLock(g_configMutex);
    g_config.length = length;
    epicsMutexUnlock(g_configMutex);
}
/*.$enddef${AOs::SetLength} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$define${AOs::SetCycles} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::SetCycles} .......................................................*/
void SetCycles(uint32_t cycles) {
    epicsMutexLock(g_configMutex);
    g_config.rep.cycles = cycles;
    epicsMutexUnlock(g_configMutex);
}
/*.$enddef${AOs::SetCycles} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$define${AOs::SetSCfgMode} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::SetSCfgMode} .....................................................*/
void SetSCfgMode(enum StartMode mode) {
    epicsMutexLock(g_configMutex);
    g_config.start.mode = mode;
    epicsMutexUnlock(g_configMutex);
}
/*.$enddef${AOs::SetSCfgMode} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$define${AOs::SetSCfgModuloDivisor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::SetSCfgModuloDivisor} ............................................*/
void SetSCfgModuloDivisor(uint32_t divisor) {
    epicsMutexLock(g_configMutex);
    g_config.start.moduloDivisor = divisor;
    epicsMutexUnlock(g_configMutex);
}
/*.$enddef${AOs::SetSCfgModuloDivisor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$define${AOs::SetSCfgModuloOffset} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::SetSCfgModuloOffset} .............................................*/
void SetSCfgModuloOffset(uint32_t offset) {
    epicsMutexLock(g_configMutex);
    g_config.start.moduloOffset = offset;
    epicsMutexUnlock(g_configMutex);
}
/*.$enddef${AOs::SetSCfgModuloOffset} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/* config getter */
/*.$define${AOs::GetConfig} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::GetConfig} .......................................................*/
static void GetConfig(Configuration* config) {
    epicsMutexLock(g_configMutex);
    *config = g_config;
    epicsMutexUnlock(g_configMutex);
}
/*.$enddef${AOs::GetConfig} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/


/* Philo definition --------------------------------------------------------*/
/*.$define${AOs::SeqCtrl_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::SeqCtrl_ctor} ....................................................*/
void SeqCtrl_ctor(void) {
    /* init global variables */
    g_configMutex = epicsMutexCreate();
    ConfigurationInit(&g_config);

    QActive_ctor(&l_seqCtrl.super, Q_STATE_CAST(&SeqCtrl_initial));

    QF_poolInit(l_qEvt, sizeof(l_qEvt), sizeof(l_qEvt[0]));
    QF_poolInit(l_evtStoStartOfSeq, sizeof(l_evtStoStartOfSeq),
        sizeof(l_evtStoStartOfSeq[0]));

    QACTIVE_START(&l_seqCtrl.super,
        (uint_fast8_t) 1,
        l_SeqCtrlQueueSto,
        Q_DIM(l_SeqCtrlQueueSto),
        (void *) 0,
        0U,
        (QEvt *)0);
}
/*.$enddef${AOs::SeqCtrl_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$define${AOs::SeqCtrl} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::SeqCtrl} .........................................................*/
/*.${AOs::SeqCtrl::SM} .....................................................*/
static QState SeqCtrl_initial(SeqCtrl * const me, QEvt const * const e) {
    /*.${AOs::SeqCtrl::SM::initial} */
    /* init extended state variables */
    me->index = 0;
    me->count = 0;
    ConfigurationInit(&me->config);

    /* init qspy dictionaries */
    QS_OBJ_DICTIONARY(&l_seqCtrl);
    QS_FUN_DICTIONARY(&QHsm_top);

    QS_FUN_DICTIONARY(&SeqCtrl_stopped);
    QS_FUN_DICTIONARY(&SeqCtrl_running);
    QS_FUN_DICTIONARY(&SeqCtrl_init);
    QS_FUN_DICTIONARY(&SeqCtrl_play);

    QS_SIG_DICTIONARY(START_SIG, (void *)0);
    QS_SIG_DICTIONARY(STOP_SIG, (void *)0);
    QS_SIG_DICTIONARY(SOS_SIG, (void *)0);
    QS_SIG_DICTIONARY(STEP_SIG, (void *)0);
    QS_SIG_DICTIONARY(SOP_SIG, (void *)0);
    return Q_TRAN(&SeqCtrl_stopped);
}
/*.${AOs::SeqCtrl::SM::root} ...............................................*/
static QState SeqCtrl_root(SeqCtrl * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${AOs::SeqCtrl::SM::root::SOS} */
        case SOS_SIG: {
            QEvent *evt = NULL;
            PulseIdEvt *pulseIdEvt = NULL;

            evt = Q_NEW(QEvt, SOP_SIG);
            QACTIVE_POST_LIFO(AO_SeqCtrl, evt);

            pulseIdEvt = Q_NEW(PulseIdEvt, STEP_SIG);
            pulseIdEvt->pulse_id = Q_EVT_CAST(PulseIdEvt)->pulse_id;
            QACTIVE_POST_LIFO(AO_SeqCtrl, &pulseIdEvt->super);

            status_ = Q_HANDLED();
            break;
        }
        /*.${AOs::SeqCtrl::SM::root::SOP} */
        case SOP_SIG: {
            SeqCtrl_SetSop(0);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*.${AOs::SeqCtrl::SM::root::stopped} ......................................*/
static QState SeqCtrl_stopped(SeqCtrl * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${AOs::SeqCtrl::SM::root::stopped} */
        case Q_ENTRY_SIG: {
            me->index = 0;
            me->count = 0;
            status_ = Q_HANDLED();
            break;
        }
        /*.${AOs::SeqCtrl::SM::root::stopped::START} */
        case START_SIG: {
            status_ = Q_TRAN(&SeqCtrl_waiting);
            break;
        }
        default: {
            status_ = Q_SUPER(&SeqCtrl_root);
            break;
        }
    }
    return status_;
}
/*.${AOs::SeqCtrl::SM::root::running} ......................................*/
static QState SeqCtrl_running(SeqCtrl * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${AOs::SeqCtrl::SM::root::running} */
        case Q_ENTRY_SIG: {
            SeqCtrl_SetLoad(0);
            SeqCtrl_SetIsRunning(1);
            GetConfig(&me->config);
            status_ = Q_HANDLED();
            break;
        }
        /*.${AOs::SeqCtrl::SM::root::running} */
        case Q_EXIT_SIG: {
            SeqCtrl_SetIsRunning(0);
            SeqCtrl_SetIsEnabled(false);
            status_ = Q_HANDLED();
            break;
        }
        /*.${AOs::SeqCtrl::SM::root::running::STOP} */
        case STOP_SIG: {
            status_ = Q_TRAN(&SeqCtrl_stopped);
            break;
        }
        /*.${AOs::SeqCtrl::SM::root::running::STEP} */
        case STEP_SIG: {
            status_ = Q_TRAN(&SeqCtrl_stopped);
            break;
        }
        default: {
            status_ = Q_SUPER(&SeqCtrl_root);
            break;
        }
    }
    return status_;
}
/*.${AOs::SeqCtrl::SM::root::running::waiting} .............................*/
static QState SeqCtrl_waiting(SeqCtrl * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${AOs::SeqCtrl::SM::root::running::waiting::STEP} */
        case STEP_SIG: {
            /*.${AOs::SeqCtrl::SM::root::running::waiting::STEP::[(length>0)&&(cycles>=0)]} */
            if ((me->config.length > 0) && (me->config.rep.cycles >= 0)) {
                /*.${AOs::SeqCtrl::SM::root::running::waiting::STEP::[(length>0)&&(cy~::[mode==START_MODULO]} */
                if ((me->config.start.mode == START_MODULO)
)
                {
                    /*printf("pid=%" PRIu64 ", divisor=%" PRIu32 ", offset=%" PRIu32 "\n", Q_EVT_CAST(PulseIdEvt)->pulse_id, me->config.start.moduloDivisor, me->config.start.moduloOffset);*/
                    /*.${AOs::SeqCtrl::SM::root::running::waiting::STEP::[(length>0)&&(cy~::[mode==START_MOD~::[(pulseid%divisor)-offset==0]} */
                    if (((Q_EVT_CAST(PulseIdEvt)->pulse_id % me->config.start.moduloDivisor) - me->config.start.moduloOffset) == 0) {
                        /*printf("-> pid=%" PRIu64 ", divisor=%" PRIu32 ", offset=%" PRIu32 "\n", Q_EVT_CAST(PulseIdEvt)->pulse_id, me->config.start.moduloDivisor, me->config.start.moduloOffset);*/
                        SeqCtrl_SetStartedAt(Q_EVT_CAST(PulseIdEvt)->pulse_id);
                        SeqCtrl_SetIsEnabled(true);
                        status_ = Q_TRAN(&SeqCtrl_play);
                    }
                    /*.${AOs::SeqCtrl::SM::root::running::waiting::STEP::[(length>0)&&(cy~::[mode==START_MOD~::[else]} */
                    else {
                        status_ = Q_TRAN(&SeqCtrl_waiting);
                    }
                }
                /*.${AOs::SeqCtrl::SM::root::running::waiting::STEP::[(length>0)&&(cy~::[mode==START_IMMEDIATELY]} */
                else if (me->config.start.mode == START_IMMEDIATELY) {
                    SeqCtrl_SetStartedAt(Q_EVT_CAST(PulseIdEvt)->pulse_id);
                    SeqCtrl_SetIsEnabled(true);
                    status_ = Q_TRAN(&SeqCtrl_play);
                }
                else {
                    status_ = Q_UNHANDLED();
                }
            }
            else {
                status_ = Q_UNHANDLED();
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&SeqCtrl_running);
            break;
        }
    }
    return status_;
}
/*.${AOs::SeqCtrl::SM::root::running::play} ................................*/
static QState SeqCtrl_play(SeqCtrl * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${AOs::SeqCtrl::SM::root::running::play} */
        case Q_ENTRY_SIG: {
            SeqCtrl_SetIndex(me->index);
            me->index++;
            if (me->index >= me->config.length) {
              me->index = 0;
              me->count++;
            }
            status_ = Q_HANDLED();
            break;
        }
        /*.${AOs::SeqCtrl::SM::root::running::play::STEP} */
        case STEP_SIG: {
            /*.${AOs::SeqCtrl::SM::root::running::play::STEP::[(cycles==0)||(count<cycles)]} */
            if ((me->config.rep.cycles == 0) || (me->count < me->config.rep.cycles)) {
                status_ = Q_TRAN(&SeqCtrl_play);
            }
            else {
                status_ = Q_UNHANDLED();
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&SeqCtrl_running);
            break;
        }
    }
    return status_;
}
/*.$enddef${AOs::SeqCtrl} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

void QV_onIdle(void) {
    /* EPICS cooperative environment: do nothing */
}
