/*.$file${.::seqCtrl.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: seqCtrl.qm
* File:  ${.::seqCtrl.h}
*
* This code has been generated by QM 5.0.1 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*.$endhead${.::seqCtrl.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef SEQ_CTRL_H
#define SEQ_QTRL_H

#include "qpc.h"

/* start configurations */
enum StartMode {
    START_IMMEDIATELY,
    START_MODULO
};

/* events */
enum SeqCtrl {
    START_SIG = Q_USER_SIG,
    STOP_SIG,
    SOS_SIG,
    STEP_SIG,
    SOP_SIG,
    MAX_SIG
};

/*.$declare${Events::PulseIdEvt} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${Events::PulseIdEvt} ...................................................*/
typedef struct {
/* protected: */
    QEvt super;

/* public: */
    uint64_t pulse_id;
} PulseIdEvt;
/*.$enddecl${Events::PulseIdEvt} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/* data */
/*.$declare${AOs::SetLength} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::SetLength} .......................................................*/
void SetLength(uint32_t length);
/*.$enddecl${AOs::SetLength} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$declare${AOs::SetCycles} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::SetCycles} .......................................................*/
void SetCycles(uint32_t cycles);
/*.$enddecl${AOs::SetCycles} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$declare${AOs::SetSCfgMode} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::SetSCfgMode} .....................................................*/
void SetSCfgMode(enum StartMode mode);
/*.$enddecl${AOs::SetSCfgMode} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$declare${AOs::SetSCfgModuloDivisor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::SetSCfgModuloDivisor} ............................................*/
void SetSCfgModuloDivisor(uint32_t divisor);
/*.$enddecl${AOs::SetSCfgModuloDivisor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$declare${AOs::SetSCfgModuloOffset} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::SetSCfgModuloOffset} .............................................*/
void SetSCfgModuloOffset(uint32_t offset);
/*.$enddecl${AOs::SetSCfgModuloOffset} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/


/* output */
extern void SeqCtrl_SetIndex(uint32_t index);
extern void SeqCtrl_SetLoad(long dummy);
extern void SeqCtrl_SetSop(long dummy);
extern void SeqCtrl_SetIsRunning(long is_running);
extern void SeqCtrl_SetIsEnabled(long is_enabled);
extern void SeqCtrl_SetStartedAt(uint64_t pulse_id);


/* active object */
/*.$declare${AOs::SeqCtrl_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::SeqCtrl_ctor} ....................................................*/
void SeqCtrl_ctor(void);
/*.$enddecl${AOs::SeqCtrl_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$declare${AOs::AO_SeqCtrl} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
extern QMActive * const AO_SeqCtrl;
/*.$enddecl${AOs::AO_SeqCtrl} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

#endif